-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1

local SafeNumber = require("MemorySafe.SafeNumber")

local __meta__ = {
    __index = function(t, k)
        local val = rawget(t, '_' .. k)
        if not val then return nil end
        if type(val) == "string" then
            return GetLanguageText(val)
        elseif type(val) == "table" then
            local list = {}
            for i, v in ipairs(val) do
                list[i] = GetLanguageText(v)
            end
            return list
        else
            return val
        end
    end
}

local tab = {}

---@type TItem[]
tab.Item = {
    setmetatable({ ID = 1, _Name = "金币", Type = 4, ItemSubType = 0, Time = 0, Renewal = 0, _Desc = "金币描述", Quality = 0, Icon = "1", IconOpen = "", DropType = 0, DropPrefab = "coin", Effect = 0, Talent = 0, Drop = {  }, UnlockTime = 0, UnlockCost = {  }, Star = 0, AppearanceType = 0, Appearance = {  }, Character = {  }, Weight = 0, MergeMaterials = {  }, SubType = 0, Set = 0, Merge = 0, WearPrefab = "", BasicAttribute = {  }, _ExtraAttributeDesc = {  }, LevelAttribute = {  }, StarAttribute = {  }, Skill = 0, Conversion = {  }, HeroIcon = "", PrimaryElement = 0, ElementAttribute = {  }, NextStar = 0, MaterialExp = 0 }, __meta__),
    setmetatable({ ID = 2, _Name = "宝石", Type = 5, ItemSubType = 0, Time = 0, Renewal = 0, _Desc = "宝石描述", Quality = 4, Icon = "2", IconOpen = "", DropType = 0, DropPrefab = "diamond", Effect = 0, Talent = 0, Drop = {  }, UnlockTime = 0, UnlockCost = {  }, Star = 0, AppearanceType = 0, Appearance = {  }, Character = {  }, Weight = 0, MergeMaterials = {  }, SubType = 0, Set = 0, Merge = 0, WearPrefab = "", BasicAttribute = {  }, _ExtraAttributeDesc = {  }, LevelAttribute = {  }, StarAttribute = {  }, Skill = 0, Conversion = {  }, HeroIcon = "", PrimaryElement = 0, ElementAttribute = {  }, NextStar = 0, MaterialExp = 0 }, __meta__),
}

tab.ItemByID = {}
for _, rec in pairs(tab.Item) do
	tab.ItemByID[rec.ID] = rec
end

tab.Enum = {
	Quality = {
		Normal = 0,
		Fine = 1,
		Excellent = 2,
		Epic = 3,
		Gold = 4,
		Red = 5,
		Dream = 6,
	},
	ItemType = {
		None = 0,
		Material = 1,
		Equipment = 2,
		Potion = 3,
		Coin = 4,
		Diamonds = 5,
		Sp = 6,
		RoleExp = 7,
		FightExp = 8,
		Talent = 9,
		Hero = 10,
		Chest = 11,
		CollectionPart = 12,
		AutoUse = 13,
		ProductTag = 14,
		SuperWeapon = 15,
		AccumulatePoints = 16,
		Activity = 17,
		TimeLimit = 18,
		EnergyStone = 19,
		UAV = 20,
		TaskExp = 21,
		BattlepassExp = 22,
		ChallengeCoin = 23,
		EndlessPT = 28,
		TalentRuneStone = 29,
		Skin = 30,
		ExclusiveWeapon = 31,
	},
	EquipSubType = {
		Weapon = 0,
		Hat = 1,
		Gloves = 2,
		Clothes = 3,
		Shoes = 4,
		Pants = 5,
		UAV = 6,
	},
	DropType = {
		None = 0,
		Ring = 1,
		Beam = 2,
		Flash = 3,
	},
	AppearType = {
		Model = 0,
		Smoke = 1,
		Halo = 2,
	},
	ElementType = {
		None = 0,
		All = 1,
		Fire = 2,
		Ice = 3,
		Lightning = 4,
		Poison = 5,
	},
	ItemSubType = {
		None = 0,
		ElementalStone = 1,
		IngotBar = 2,
	},
}

return tab