-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1

local SafeNumber = require("MemorySafe.SafeNumber")

local __meta__ = {
    __index = function(t, k)
        local val = rawget(t, '_' .. k)
        if not val then return nil end
        if type(val) == "string" then
            return GetLanguageText(val)
        elseif type(val) == "table" then
            local list = {}
            for i, v in ipairs(val) do
                list[i] = GetLanguageText(v)
            end
            return list
        else
            return val
        end
    end
}

local tab = {}

---@type TMallItem[]
tab.MallItem = {
    setmetatable({ ID = 1, ItemID = 1, _Title = "Pile of Gems", ProductId = "com.sagi.barrettcn.gem1", Items = { [2] = SafeNumber(80) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2, ItemID = 2, _Title = "Heap of Gems", ProductId = "com.sagi.barrettcn.gem2", Items = { [2] = SafeNumber(500) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3, ItemID = 3, _Title = "Bucket of Gems", ProductId = "com.sagi.barrettcn.gem3", Items = { [2] = SafeNumber(1200) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 4, ItemID = 4, _Title = "Barrel of Gems", ProductId = "com.sagi.barrettcn.gem4", Items = { [2] = SafeNumber(2500) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 5, ItemID = 5, _Title = "Chest of Gems", ProductId = "com.sagi.barrettcn.gem5", Items = { [2] = SafeNumber(6500) }, Price = 32800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 6, ItemID = 6, _Title = "Cart of Gems", ProductId = "com.sagi.barrettcn.gem6", Items = { [2] = SafeNumber(14000) }, Price = 64800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 105, ItemID = 104, _Title = "hero_104", ProductId = "com.sagi.barrettcn.buy_hero104", Items = { [104] = SafeNumber(1) }, Price = 1200, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 106, ItemID = 104, _Title = "hero_106", ProductId = "com.sagi.barrettcn.buy_hero106", Items = { [106] = SafeNumber(1) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1004, ItemID = 1004, _Title = "Novice Gift Pack", ProductId = "com.sagi.barrettcn.gift_novice02", Items = { [2] = SafeNumber(150),[21213] = SafeNumber(1),[1] = SafeNumber(15000),[1002] = SafeNumber(30) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1003, ItemID = 1003, _Title = "艾薇儿限定礼包", ProductId = "com.sagi.barrettcn.gift_hero105", Items = { [1] = SafeNumber(10000),[105] = SafeNumber(1),[1005] = SafeNumber(30) }, Price = 12800, Replenishment = { [2] = 2500 } }, __meta__),
    setmetatable({ ID = 1005, ItemID = 1005, _Title = "伊芙角色礼包", ProductId = "com.sagi.barrettcn.gift_hero107", Items = { [1] = SafeNumber(10000),[107] = SafeNumber(1),[1007] = SafeNumber(30) }, Price = 12800, Replenishment = { [2] = 2500 } }, __meta__),
    setmetatable({ ID = 1006, ItemID = 1006, _Title = "凯瑟琳限定礼包", ProductId = "com.sagi.barrettcn.gift_hero109", Items = { [1] = SafeNumber(10000),[109] = SafeNumber(1),[1009] = SafeNumber(30) }, Price = 12800, Replenishment = { [2] = 2500 } }, __meta__),
    setmetatable({ ID = 1007, ItemID = 1007, _Title = "限时英雄1", ProductId = "com.sagi.barrettcn.gift_newhero1", Items = { [1] = SafeNumber(10000),[111] = SafeNumber(1),[1011] = SafeNumber(30) }, Price = 12800, Replenishment = { [2] = 2500 } }, __meta__),
    setmetatable({ ID = 2001, ItemID = 2001, _Title = "Piggy bank", ProductId = "com.sagi.barrettcn.piggy_bank", Items = { [21] = SafeNumber(1) }, Price = 3000, Replenishment = { [2] = 500 } }, __meta__),
    setmetatable({ ID = 2002, ItemID = 2002, _Title = "去广告", ProductId = "com.sagi.barrettcn.noads", Items = { [22] = SafeNumber(1) }, Price = 2500, Replenishment = { [2] = 400 } }, __meta__),
    setmetatable({ ID = 2003, ItemID = 2003, _Title = "赛季通行证", ProductId = "com.sagi.barrettcn.battle_pass", Items = { [23] = SafeNumber(1) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2004, ItemID = 2004, _Title = "回归礼包", ProductId = "com.sagi.barrettcn.recallpack", Items = { [2] = SafeNumber(300),[1] = SafeNumber(10000),[11] = SafeNumber(1),[20002] = SafeNumber(1),[100000] = SafeNumber(20),[1000] = SafeNumber(10),[12] = SafeNumber(1) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2005, ItemID = 2005, _Title = "许愿翻倍", ProductId = "com.sagi.barrettcn.wish", Items = {  }, Price = 600, Replenishment = { [2] = 80 } }, __meta__),
    setmetatable({ ID = 2007, ItemID = 2007, _Title = "任务通行证", ProductId = "com.sagi.barrettcn.taskpass", Items = { [25] = SafeNumber(1) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1011, ItemID = 1011, _Title = "维姬的少女时代", ProductId = "com.sagi.barrettcn.hero101pf4_1", Items = { [1] = SafeNumber(2000),[1001] = SafeNumber(30) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1012, ItemID = 1012, _Title = "维姬的中学时代", ProductId = "com.sagi.barrettcn.hero101pf4_2", Items = { [1] = SafeNumber(8000),[1001] = SafeNumber(60) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1013, ItemID = 1013, _Title = "维姬的高中时代", ProductId = "com.sagi.barrettcn.hero101pf4_3", Items = { [1] = SafeNumber(20000),[1001] = SafeNumber(100) }, Price = 4500, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1014, ItemID = 1014, _Title = "维姬的大学时代", ProductId = "com.sagi.barrettcn.hero101pf4_4", Items = { [1] = SafeNumber(50000),[1001] = SafeNumber(200) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1021, ItemID = 1021, _Title = "凯莉的烟熏妆", ProductId = "com.sagi.barrettcn.hero102pf4_1", Items = { [1] = SafeNumber(3000),[1002] = SafeNumber(30) }, Price = 1200, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1022, ItemID = 1022, _Title = "凯莉的柳钉装", ProductId = "com.sagi.barrettcn.hero102pf4_2", Items = { [1] = SafeNumber(12000),[1002] = SafeNumber(60) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1023, ItemID = 1023, _Title = "凯莉的摇滚乐", ProductId = "com.sagi.barrettcn.hero102pf4_3", Items = { [1] = SafeNumber(30000),[1002] = SafeNumber(100) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1024, ItemID = 1024, _Title = "凯莉的朋克信仰", ProductId = "com.sagi.barrettcn.hero102pf4_4", Items = { [1] = SafeNumber(75000),[1002] = SafeNumber(200) }, Price = 19800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1031, ItemID = 1031, _Title = "卢卡尔的低级科技", ProductId = "com.sagi.barrettcn.hero103pf4_1", Items = { [1] = SafeNumber(4000),[1003] = SafeNumber(30) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1032, ItemID = 1032, _Title = "卢卡尔的中级科技", ProductId = "com.sagi.barrettcn.hero103pf4_2", Items = { [1] = SafeNumber(16000),[1003] = SafeNumber(60) }, Price = 4500, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1033, ItemID = 1033, _Title = "卢卡尔的高级科技", ProductId = "com.sagi.barrettcn.hero103pf4_3", Items = { [1] = SafeNumber(40000),[1003] = SafeNumber(100) }, Price = 9800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1034, ItemID = 1034, _Title = "卢卡尔的终极科技", ProductId = "com.sagi.barrettcn.hero103pf4_4", Items = { [1] = SafeNumber(100000),[1003] = SafeNumber(200) }, Price = 25800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1041, ItemID = 1041, _Title = "兰博的哑铃", ProductId = "com.sagi.barrettcn.hero104pf4_1", Items = { [1] = SafeNumber(6000),[1004] = SafeNumber(30) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1042, ItemID = 1042, _Title = "兰博的卧推板", ProductId = "com.sagi.barrettcn.hero104pf4_2", Items = { [1] = SafeNumber(24000),[1004] = SafeNumber(60) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1043, ItemID = 1043, _Title = "兰博的蛋白粉", ProductId = "com.sagi.barrettcn.hero104pf4_3", Items = { [1] = SafeNumber(60000),[1004] = SafeNumber(100) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1044, ItemID = 1044, _Title = "兰博的健身房", ProductId = "com.sagi.barrettcn.hero104pf4_4", Items = { [1] = SafeNumber(120000),[1004] = SafeNumber(200) }, Price = 38800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1051, ItemID = 1051, _Title = "艾薇儿的口红", ProductId = "com.sagi.barrettcn.hero105pf5_1", Items = { [1] = SafeNumber(10000),[1005] = SafeNumber(30) }, Price = 4000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1052, ItemID = 1052, _Title = "艾薇儿的睫毛膏", ProductId = "com.sagi.barrettcn.hero105pf5_2", Items = { [1] = SafeNumber(32000),[1005] = SafeNumber(60) }, Price = 9800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1053, ItemID = 1053, _Title = "艾薇儿的隔离霜", ProductId = "com.sagi.barrettcn.hero105pf5_3", Items = { [1] = SafeNumber(80000),[1005] = SafeNumber(100) }, Price = 19800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1054, ItemID = 1054, _Title = "艾薇儿的名牌包", ProductId = "com.sagi.barrettcn.hero105pf5_5", Items = { [1] = SafeNumber(200000),[1005] = SafeNumber(200) }, Price = 51800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1061, ItemID = 1061, _Title = "塞班的作战靴", ProductId = "com.sagi.barrettcn.hero106pf4_1", Items = { [1] = SafeNumber(10000),[1006] = SafeNumber(30) }, Price = 4000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1062, ItemID = 1062, _Title = "塞班的夜视仪", ProductId = "com.sagi.barrettcn.hero106pf4_2", Items = { [1] = SafeNumber(32000),[1006] = SafeNumber(60) }, Price = 9800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1063, ItemID = 1063, _Title = "塞班的防弹衣", ProductId = "com.sagi.barrettcn.hero106pf4_3", Items = { [1] = SafeNumber(80000),[1006] = SafeNumber(100) }, Price = 19800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1064, ItemID = 1064, _Title = "塞班的枪声定位器", ProductId = "com.sagi.barrettcn.hero106pf4_4", Items = { [1] = SafeNumber(200000),[1006] = SafeNumber(200) }, Price = 51800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1071, ItemID = 1071, _Title = "伊芙的录音笔", ProductId = "com.sagi.barrettcn.hero107pf4_1", Items = { [1] = SafeNumber(10000),[1007] = SafeNumber(30) }, Price = 4000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1072, ItemID = 1072, _Title = "伊芙的窃听器", ProductId = "com.sagi.barrettcn.hero107pf4_2", Items = { [1] = SafeNumber(32000),[1007] = SafeNumber(60) }, Price = 9800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1073, ItemID = 1073, _Title = "伊芙的档案袋", ProductId = "com.sagi.barrettcn.hero107pf4_3", Items = { [1] = SafeNumber(80000),[1007] = SafeNumber(100) }, Price = 19800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1074, ItemID = 1074, _Title = "伊芙的通缉令", ProductId = "com.sagi.barrettcn.hero107pf4_4", Items = { [1] = SafeNumber(200000),[1007] = SafeNumber(200) }, Price = 51800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1081, ItemID = 1081, _Title = "巴耶克的先知手札", ProductId = "com.sagi.barrettcn.hero108pf4_1", Items = { [2] = SafeNumber(200),[1] = SafeNumber(20000),[1008] = SafeNumber(30) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1082, ItemID = 1082, _Title = "巴耶克的狱火装置", ProductId = "com.sagi.barrettcn.hero108pf4_2", Items = { [2] = SafeNumber(500),[1] = SafeNumber(50000),[1008] = SafeNumber(60) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1083, ItemID = 1083, _Title = "巴耶克的巨兽臂铠", ProductId = "com.sagi.barrettcn.hero108pf4_3", Items = { [2] = SafeNumber(1000),[1] = SafeNumber(100000),[1008] = SafeNumber(100) }, Price = 25800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1084, ItemID = 1084, _Title = "巴耶克的传承重器", ProductId = "com.sagi.barrettcn.hero108pf4_4", Items = { [2] = SafeNumber(2000),[1] = SafeNumber(200000),[1008] = SafeNumber(200) }, Price = 64800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1091, ItemID = 1091, _Title = "凯瑟琳的手弩瞄具", ProductId = "com.sagi.barrettcn.hero109pf4_1", Items = { [2] = SafeNumber(200),[1] = SafeNumber(20000),[1009] = SafeNumber(30) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1092, ItemID = 1092, _Title = "凯瑟琳的振金耳环", ProductId = "com.sagi.barrettcn.hero109pf4_2", Items = { [2] = SafeNumber(500),[1] = SafeNumber(50000),[1009] = SafeNumber(60) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1093, ItemID = 1093, _Title = "凯瑟琳的荧光披风", ProductId = "com.sagi.barrettcn.hero109pf4_3", Items = { [2] = SafeNumber(1000),[1] = SafeNumber(100000),[1009] = SafeNumber(100) }, Price = 25800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1094, ItemID = 1094, _Title = "凯瑟琳的淬毒配方", ProductId = "com.sagi.barrettcn.hero109pf4_4", Items = { [2] = SafeNumber(2000),[1] = SafeNumber(200000),[1009] = SafeNumber(200) }, Price = 64800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1101, ItemID = 1101, _Title = "半藏的护额", ProductId = "com.sagi.barrettcn.hero111pf4_1", Items = { [2] = SafeNumber(200),[1] = SafeNumber(20000),[1011] = SafeNumber(30) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1102, ItemID = 1102, _Title = "半藏的忍者面罩", ProductId = "com.sagi.barrettcn.hero111pf4_2", Items = { [2] = SafeNumber(500),[1] = SafeNumber(50000),[1011] = SafeNumber(60) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1103, ItemID = 1103, _Title = "半藏的高科技义眼", ProductId = "com.sagi.barrettcn.hero111pf4_3", Items = { [2] = SafeNumber(1000),[1] = SafeNumber(100000),[1011] = SafeNumber(100) }, Price = 25800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1104, ItemID = 1104, _Title = "半藏的妖刀村正", ProductId = "com.sagi.barrettcn.hero111pf4_4", Items = { [2] = SafeNumber(2000),[1] = SafeNumber(200000),[1011] = SafeNumber(200) }, Price = 64800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3001, ItemID = 3001, _Title = "零散的材料", ProductId = "com.sagi.barrettcn.qianghua_01", Items = { [1] = SafeNumber(1000),[100000] = SafeNumber(100) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3002, ItemID = 3002, _Title = "少量的材料", ProductId = "com.sagi.barrettcn.qianghua_02", Items = { [1] = SafeNumber(5000),[100000] = SafeNumber(200) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3003, ItemID = 3003, _Title = "一盒子的材料", ProductId = "com.sagi.barrettcn.qianghua_03", Items = { [1] = SafeNumber(20000),[100000] = SafeNumber(500) }, Price = 6000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3004, ItemID = 3004, _Title = "一小车的材料", ProductId = "com.sagi.barrettcn.qianghua_04", Items = { [1] = SafeNumber(50000),[100000] = SafeNumber(1000) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3005, ItemID = 3005, _Title = "成堆的材料", ProductId = "com.sagi.barrettcn.qianghua_05", Items = { [1] = SafeNumber(100000),[100000] = SafeNumber(2500) }, Price = 32800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 3006, ItemID = 3006, _Title = "海量的材料", ProductId = "com.sagi.barrettcn.qianghua_06", Items = { [1] = SafeNumber(200000),[100000] = SafeNumber(5000) }, Price = 64800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 1900, ItemID = 1900, _Title = "宝石特惠礼包", ProductId = "com.sagi.barrettcn.gift_gemoff", Items = { [2] = SafeNumber(3200) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8101, ItemID = 8101, _Title = "超级天赋礼包", ProductId = "com.sagi.barrettcn.gift_minipacksuper", Items = { [1] = SafeNumber(101) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8201, ItemID = 8201, _Title = "超值金币", ProductId = "com.sagi.barrettcn.gift_minipack1", Items = { [1] = SafeNumber(201) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8202, ItemID = 8202, _Title = "超值材料1", ProductId = "com.sagi.barrettcn.gift_minipack2", Items = { [1] = SafeNumber(202) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8203, ItemID = 8203, _Title = "超值材料2", ProductId = "com.sagi.barrettcn.gift_minipack3", Items = { [1] = SafeNumber(203) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8204, ItemID = 8204, _Title = "超值材料3", ProductId = "com.sagi.barrettcn.gift_minipack4", Items = { [1] = SafeNumber(204) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8205, ItemID = 8205, _Title = "超值材料4", ProductId = "com.sagi.barrettcn.gift_minipack5", Items = { [1] = SafeNumber(205) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8206, ItemID = 8206, _Title = "超值材料5", ProductId = "com.sagi.barrettcn.gift_minipack6", Items = { [1] = SafeNumber(206) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8301, ItemID = 8301, _Title = "节日宝石大礼包", ProductId = "com.sagi.barrettcn.festivals_giftbig", Items = { [2] = SafeNumber(600),[111] = SafeNumber(1),[1011] = SafeNumber(30),[35] = SafeNumber(10) }, Price = 12800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8302, ItemID = 8302, _Title = "节日超级武器大礼包", ProductId = "com.sagi.barrettcn.festivals_giftmid", Items = { [2] = SafeNumber(300),[106] = SafeNumber(1),[1006] = SafeNumber(20),[35] = SafeNumber(10) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8303, ItemID = 8303, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift1", Items = { [2] = SafeNumber(300),[1] = SafeNumber(30000),[1005] = SafeNumber(15),[35] = SafeNumber(10) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8304, ItemID = 8304, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift2", Items = { [2] = SafeNumber(300),[1] = SafeNumber(30000),[1008] = SafeNumber(15),[35] = SafeNumber(10) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8305, ItemID = 8305, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift3", Items = { [2] = SafeNumber(300),[1] = SafeNumber(30000),[1007] = SafeNumber(15),[35] = SafeNumber(10) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8306, ItemID = 8306, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift4", Items = { [2] = SafeNumber(270),[64] = SafeNumber(10),[63] = SafeNumber(30),[62] = SafeNumber(120) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8307, ItemID = 8307, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift5", Items = { [1] = SafeNumber(60000),[100000] = SafeNumber(200),[1000] = SafeNumber(15) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8308, ItemID = 8308, _Title = "节日主题礼包", ProductId = "com.sagi.barrettcn.festivals_gift6", Items = { [1] = SafeNumber(100000),[35] = SafeNumber(10) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8400, ItemID = 8400, _Title = "通行证去广告礼包", ProductId = "com.sagi.barrettcn.gift_poweruppass", Items = { [2] = SafeNumber(800),[1] = SafeNumber(100000),[23] = SafeNumber(1),[24] = SafeNumber(1) }, Price = 3000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8401, ItemID = 8401, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup1", Items = { [2] = SafeNumber(640),[110011] = SafeNumber(100),[110012] = SafeNumber(80),[110102] = SafeNumber(80) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8402, ItemID = 8402, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup2", Items = { [1] = SafeNumber(100000),[1005] = SafeNumber(20),[100000] = SafeNumber(100),[12] = SafeNumber(6) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8403, ItemID = 8403, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup3", Items = { [1] = SafeNumber(100000),[100000] = SafeNumber(100),[12] = SafeNumber(6),[1006] = SafeNumber(25) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8404, ItemID = 8404, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup4", Items = { [1] = SafeNumber(100000),[1007] = SafeNumber(20),[100000] = SafeNumber(100),[12] = SafeNumber(6) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8405, ItemID = 8405, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup5", Items = { [1] = SafeNumber(100000),[100000] = SafeNumber(100),[12] = SafeNumber(6),[1008] = SafeNumber(20) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 8406, ItemID = 8406, _Title = "实力提升礼包", ProductId = "com.sagi.barrettcn.gift_powerup6", Items = { [1] = SafeNumber(100000),[1009] = SafeNumber(20),[100000] = SafeNumber(100),[12] = SafeNumber(6) }, Price = 5000, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2101, ItemID = 2101, _Title = "月卡1", ProductId = "com.sagi.barrettcn.monthlybag", Items = { [2] = SafeNumber(300),[8] = SafeNumber(10) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2102, ItemID = 2102, _Title = "月卡2", ProductId = "com.sagi.barrettcn.permanentbag", Items = { [2] = SafeNumber(1200),[1] = SafeNumber(100000) }, Price = 6800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2151, ItemID = 2151, _Title = "每日礼包1", ProductId = "com.sagi.barrettcn.dailytaskgift1", Items = { [2] = SafeNumber(80),[1] = SafeNumber(10000),[2000] = SafeNumber(2) }, Price = 300, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2152, ItemID = 2152, _Title = "每日礼包2", ProductId = "com.sagi.barrettcn.dailytaskgift2", Items = { [2] = SafeNumber(120),[110012] = SafeNumber(20),[13] = SafeNumber(2) }, Price = 600, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2153, ItemID = 2153, _Title = "每日礼包3", ProductId = "com.sagi.barrettcn.dailytaskgift3", Items = { [2] = SafeNumber(200),[12] = SafeNumber(2),[110011] = SafeNumber(100),[8] = SafeNumber(2) }, Price = 800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2161, ItemID = 2161, _Title = "每周礼包1", ProductId = "com.sagi.barrettcn.weeklytaskgift1", Items = { [2] = SafeNumber(350),[1] = SafeNumber(80000),[3] = SafeNumber(100) }, Price = 1800, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2162, ItemID = 2162, _Title = "每周礼包2", ProductId = "com.sagi.barrettcn.weeklytaskgift2", Items = { [2] = SafeNumber(1100),[110102] = SafeNumber(60),[8] = SafeNumber(15),[110003] = SafeNumber(1) }, Price = 4500, Replenishment = {  } }, __meta__),
    setmetatable({ ID = 2163, ItemID = 2163, _Title = "每周礼包3", ProductId = "com.sagi.barrettcn.weeklytaskgift3", Items = { [2] = SafeNumber(2700),[12] = SafeNumber(10),[110011] = SafeNumber(400),[110012] = SafeNumber(200) }, Price = 9800, Replenishment = {  } }, __meta__)
}


---@type table<number, TMallItem>
tab.MallItemByID = {}
for _, rec in pairs(tab.MallItem) do
	tab.MallItemByID[rec.ID] = rec
end

---@type table<string, TMallItem>
tab.MallItemByProductId = {}
for _, rec in pairs(tab.MallItem) do
	tab.MallItemByProductId[rec.ProductId] = rec
end

---@type table<string, TMallItem>
tab.MallItemByItemID = {}
for _, rec in pairs(tab.MallItem) do
	tab.MallItemByItemID[table.concat({rec.ItemID}, "_")] = rec
end

--find TMallItem with keys ItemID
---@param ItemID number
---@return TMallItem
function tab.Find(ItemID)
	local key = table.concat({ItemID}, "_")
	return tab.MallItemByItemID[key]
end

tab.Enum = {
	MallItemType = {
		Gem = 0,
		Hero = 1,
		Gift = 2,
		LimitGift = 3,
		HeroGift = 4,
		NoviceGift = 5,
		PiggyBank = 6,
	},
	ItemShowType = {
		Gem = 0,
		Hero = 1,
		MallItem = 2,
		HomeFloat = 3,
	},
	ShowConditionType = {
		None = 0,
		UnlockMall = 1,
		NoHero = 2,
		HasHero = 3,
		ChapterPass = 4,
	},
}

---@class TMallItem
---@field public ID number
---@field public ItemID number
---@field public Title string
---@field public _Title string
---@field public ProductId string
---@field public Items TIntMap
---@field public Price number
---@field public Replenishment TIntMap

---@alias TIntMap table<number, number>

return tab