require("gist/Lua/lib/global")
local que = require("gist/Lua/lib/queue")

local q = que.new(10)

q:pushright(7)
print(q:tostring(), q:peekleft())
q:pushright(3)
print(q:tostring(), q:peekleft())
q:pushright(5)
print(q:tostring(), q:peekleft())
q:pushright(1)
print(q:tostring(), q:peekleft())
q:pushright(8)
print(q:tostring(), q:peekleft())
q:pushright(2)
print(q:tostring(), q:peekleft())
q:pushright(6)
print(q:tostring(), q:peekleft())
q:pushright(4)
print(q:tostring(), q:peekleft())
q:pushright(9)
print(q:tostring(), q:peekleft())
q:pushright(0)
print(q:tostring(), q:peekleft())
q:pushright(5)
print(q:tostring(), q:peekleft())
q:pushright(1)
print(q:tostring(), q:peekleft())
q:pushright(2)
print(q:tostring(), q:peekleft())
q:pushright(3)
print(q:tostring(), q:peekleft())
q:pushright(4)
print(q:tostring(), q:peekleft())